# Stage 1: Build the Java application with Maven
FROM maven:3.8.4-openjdk-18 AS build

# Set the working directory inside the container
WORKDIR /app

# Copy the source code
COPY . .

# Build the application
RUN mvn clean instal

FROM openjdk:18

# Set the working directory
WORKDIR /app

# Copy the JAR file from the build stage

COPY pom.xml .
COPY --from=build /app/target/ .

EXPOSE 8080
# Specify the default command to run the Java application
CMD ["java", "-jar", "Shop_Vibes-0.0.1-SNAPSHOT.jar"]
