name: Build and Deploy Docker Image

on:
  push:
    branches:
      - main  # Trigger this workflow when changes are pushed to the 'main' branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build JAR
      run: mvn clean package  # Adjust this command according to your Maven project structure

    - name: Docker Login
      run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

    - name: Build Docker Image
      run: docker build -t dilipdare/shopvibes:latest .  # Adjust the image name and tag

    - name: Push Docker Image
      run: docker push dilipdare/shopvibes:latest  # Push the image to your Docker Hub repository
